In [7]:
import nltk
import pandas as pd
from docx import Document
import os

In [8]:
'''files = list(os.listdir(os.getcwd()))
destination = os.path.join(os.getcwd(), 'pre_test')'''

In [6]:
'''for file in files:
    file = file.lower()
    if "pre" in file:
        os.rename(os.path.join(path, file), os.path.join(destination, file))'''

'for file in files:\n    file = file.lower()\n    if "pre" in file:\n        os.rename(os.path.join(path, file), os.path.join(destination, file))'

In [2]:
pre_test_path = os.path.join(os.getcwd(), 'Unlabeled_transcripts\\pre_test')
pre_test_list = os.listdir(pre_test_path)
print(pre_test_list)

['1006b-bprebtest-011.wav.docx', '1762_pretest.wav.docx', '1961pre.wav.docx', '2037_pretest.wav.docx', '2303-pre.wav.docx', '2564b-bprebtest-019.wav.docx', '3306_pretest-023.wav.docx', '4213bprebtest.wav.docx', '4444bprebtest.wav.docx', '4470b-bpre-test.wav.docx', '4753b-bprebtest.wav.docx', '4847-bprebtest.wav.docx', '5132-pretest.wav.docx', '5563bprebtest.wav.docx', '5661pre.wav.docx', '6001-pretest.wav.docx', '6067_pretest.wav.docx', '6080b-bprebtest.wav.docx', '6227bprebtest.wav.docx', '6477-pretest.wav.docx', '6544_pretest.wav.docx', '7092-pre.wav.docx', '7405_pretest.wav.docx', '8458_pretest.wav.docx', '8657bprebtest.wav.docx', '9320bprebtest.wav.docx', '9549-pretest.wav.docx', '9725b-bprebtest.wav.docx']

In [3]:
# Read actress and test-subjects' responses into a list from word document
def conversation(filename):
    '''returns a list of conversation'''
    text_A = []
    text_T = []
    doc = docx.Document(os.path.join(pre_test_path, filename))
    for p in doc.paragraphs:
        if "A:" in p.text:
            text_A.append(p.text.strip(" A: "))
        elif "T:" in p.text:
            text_T.append(p.text.strip(" T: "))
    return text_A, text_T

In [11]:
text_A_all = []
text_T_all = []
for file in pre_test_list:
    text_A, text_T = conversation(file)
    text_A_all.extend(text_A)
    text_T_all.extend(text_T)

In [13]:
# Create a dataframe to collect each actress comment and test-subjects' responses
col_names = [p[:4] for p in pre_test_list] 
df_pre = pd.DataFrame(index=text_A_all, columns = col_names)
df_pre.index.rename('Actor\'s_comments', inplace=True)
for file in pre_test_list:
    text_A, text_T = conversation(file)
    if len(text_A) > len(text_T):
        text_T.append('')
    elif len(text_A) < len(text_T):
        text_A.append('')
    new_column = pd.Series(text_T, name=file[:4], index=text_A)
    df_pre.update(new_column)

In [14]:
df_pre.head()

,1006,1762,1961,2037,2303,2564,3306,4213,4444,4470,...,6227,6477,6544,7092,7405,8458,8657,9320,9549,9725
Actor's_comments,,,,,,,,,,,,,,,,,,,,,
hi how's it going.,"I'm doing well, it's, good to see you,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"uh, what do you want to talk about today.",I want to talk about a group project. I feel l...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Okay, uh, what's problem.",he group and i just feel that we have a lot to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Um, ok here's a situation, Iâ€™m a fourth year student and really busy recently and i even need to apply for new graduate schools so i don't have enough time",no right yeah some of us noticed that you've b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yeah i would like to but i don't have time to meet you every week or every time we meet. Do you have another solution?,i mean well so you're saying you don't have ti...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Compute the length of conversation for each participant
df_summary = pd.DataFrame(index = col_names, columns=['response_count'])
df_summary.index.rename(name = 'Participant_id', inplace = True)

In [16]:
new = {}
for participant in col_names:
    new[participant] = df_pre[participant].value_counts(dropna=True).sum()
df_summary['response_count'] = list(new.values())
#new_column = pd.Series(list(new.values()), name = 'conv_length', index=sorted(list(new.keys())))
#df_summary.update(new_column)

In [19]:
total_response_count = {}
unique_words_count = {}
for participant in col_names:
    temp_list = []
    for w in list(df_pre[participant].dropna()):
        temp_list.extend(w.split())
    unique_words_count[participant] = len(set(temp_list))
    total_response_count[participant] = len(temp_list)

In [22]:
df_summary['TotalWordCount'] = list(total_response_count.values())
df_summary['avgWordCount'] = df_summary['TotalWordCount'] / df_summary['response_count']
df_summary['avgWordCount'] = df_summary['avgWordCount'].round()
df_summary['Unique_words_count'] = list(unique_words_count.values())
df_summary['Lexical_diversity'] = df_summary['Unique_words_count'] / df_summary['TotalWordCount']
df_summary['Lexical_diversity'] = df_summary['Lexical_diversity'].round(2)

In [23]:
df_summary

,response_count,TotalWordCount,avgWordCount,Unique_words_count,Lexical_diversity
Participant_id,,,,,
1006,9,521,58.0,215,0.41
1762,9,560,62.0,233,0.42
1961,12,377,31.0,182,0.48
2037,9,246,27.0,134,0.54
2303,7,514,73.0,196,0.38
2564,9,239,27.0,145,0.61
3306,9,468,52.0,205,0.44
4213,9,588,65.0,222,0.38
4444,12,786,66.0,258,0.33
4470,9,545,61.0,214,0.39
4753,13,396,30.0,199,0.50
4847,8,256,32.0,106,0.41
5132,9,473,53.0,180,0.38
5563,8,237,30.0,129,0.54
5661,14,380,27.0,200,0.53
6001,5,139,28.0,93,0.67
6067,12,405,34.0,194,0.48
6080,11,252,23.0,143,0.57
6227,8,275,34.0,147,0.53
6477,10,439,44.0,195,0.44
6544,8,170,21.0,96,0.56
7092,12,386,32.0,184,0.48
7405,7,320,46.0,151,0.47
8458,10,458,46.0,184,0.40
8657,7,502,72.0,231,0.46
9320,7,351,50.0,191,0.54
9549,9,263,29.0,141,0.54
9725,9,308,34.0,149,0.48